version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - cy-takeuchi

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    assignees:
      - cy-takeuchi
    groups:
      safe-dependencies:
        update-types: ["minor", "patch"]
      major-dependencies:
        update-types: ["major"]
    commit-message:
      prefix: chore
      prefix-development: chore(dev)
