version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "cy-takeuchi"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "cy-takeuchi"
    groups:
      safe-dependencies:
        update-types: ["minor", "patch"]
    commit-message:
      prefix: "fix"
      prefix-development: "fix(dev)"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
