import { get } from "./functions/utility";
import {
  isRecordNumber,
  isCreator,
  isCreatedTime,
  isModifier,
  isUpdatedTime,
  isSingleLineText,
  isMultiLineText,
  isRichText,
  isNumber,
  isCalc,
  isCheckBox,
  isRadioButton,
  isMultiSelect,
  isDropDown,
  isUserSelect,
  isOrganizationSelect,
  isGroupSelect,
  isDate,
  isTime,
  isDatetime,
  isLink,
  isFile,
  isLookup,
  isSubtable,
  isGroup,
  isReferenceTable,
  isCategory,
  isStatus,
  isStatusAssignee,
} from "./functions/formField";

const kintonePrettyFields = {
  get,
  isRecordNumber,
  isCreator,
  isCreatedTime,
  isModifier,
  isUpdatedTime,
  isSingleLineText,
  isMultiLineText,
  isRichText,
  isNumber,
  isCalc,
  isCheckBox,
  isRadioButton,
  isMultiSelect,
  isDropDown,
  isUserSelect,
  isOrganizationSelect,
  isGroupSelect,
  isDate,
  isTime,
  isDatetime,
  isLink,
  isFile,
  isLookup,
  isSubtable,
  isGroup,
  isReferenceTable,
  isCategory,
  isStatus,
  isStatusAssignee,
};

export { kintonePrettyFields };
